#!/usr/bin/expect -f

set ip_host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set src_file [lindex $argv 3]
set dst_path [lindex $argv 4]

# 设置超时时间
set timeout 60 

# download
spawn scp $username@$ip_host:$src_file $dst_path

# 处理 yes, no，对应第一次与 ip_host连接
# expect_before "(yes/no)?" { send "yes\r" }

# 自动输入密码；并处理执行结果
expect "(yes/no)?" { 
	send "yes\r" 
	exp_continue
} "*assword:" { 
	# 输入命令；Password: or password:
	send "$password\r" 
	exp_continue
} "100%" {
	send_user "ufo download successfully!\n"
	exit 0
} timeout {
	send_user "ufo timeout\n"	
	exit 2
} eof {
	send_user "ufo download eof\n"	
	exit 1
} 


